name: keysight_gui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  data_table_2: ^2.2.3
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  flutter_expandable_table: ^1.0.2
  flutter_hooks: ^0.18.2+1
  flutter_spinbox: ^0.8.0
  provider: ^6.0.2
  syncfusion_flutter_charts: ^19.4.56

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
